apiVersion: v1
kind: Service
metadata:
  name: node-svc
  labels:
    app: node-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: node-hello-world
